config/routes.rb
Dewey::Application.routes.draw do

  match '/', :to => redirect('/index.html')
  devise_for :users

  resources :acts
  resources :events
  resources :festivals
  resources :schedules do
      get 'page/:page', :action => :index, :on => :collection
    end
  resources :venues
  
  namespace :admin do
    resources :acts
    resources :events
    resources :festivals
    resources :schedules
    resources :venues
    resources :weblocations
  end
  match "/admin/schedules/new_child/:parent_id(.:format)" => "admin/schedules#new_child", :as => :new_admin_child 

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :links, :as => :linkable, :dependent => :destroy
  has_many :weblocations, :through => :links

  has_many :schedules, :as => :schedulable  
  
  validates :name, :presence => true
  
  accepts_nested_attributes_for :links, :reject_if => lambda { |a| a[:url].blank? }, :allow_destroy => true

  default_scope :order => 'name ASC'
  
  mount_uploader :logo, LogoUploader

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'

    # GET /admin/events
    # GET /admin/events.json
    def index
      @events = Event.all

      respond_to do |format|
        format.html 
        format.json { render :json => @events }
      end
    end

    # GET /admin/events/new
    # GET /admin/events/new.json
    def new
      @event = Event.new
      @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @event }
      end
    end

    # GET /admin/events/1/edit
    def edit
      @event = Event.find(params[:id])
      @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    end

    # POST /admin/events
    # POST /admin/events.json
    def create
      @event = Event.new(params[:event])

      respond_to do |format|
        if @event.save
          format.html { redirect_to :action => "index", :notice => 'Event was successfully updated.' }
          format.json { render :json => @event, :status => :created, :location => @event }
        else
          format.html { render :action => "new" }
          format.json { render :json => @event.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /admin/events/1
    # PUT /admin/events/1.json
    def update
      @event = Event.find(params[:id])

      respond_to do |format|
        if @event.update_attributes(params[:event])
          format.html { redirect_to :action => "index", :notice => 'Event was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @event.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/events/1
    # DELETE /admin/events/1.json
    def destroy
      @event = Event.find(params[:id])
      if Schedule.where(:schedulable_id => @event, :schedulable_type => "Event").exists?
        respond_to do |format|
          format.html { redirect_to admin_events_url, :notice => "Cannot delete the event #{@event.name} because it is referenced by one or more schedule items. Delete those first." } 
          format.json { head :ok }
        end
      else
        @event.destroy
        respond_to do |format|
          format.html { redirect_to admin_events_url, :notice => "Successfully deleted the event #{@event.name}" }
          format.json { head :ok }
        end
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # GET /events
  # GET /events.json
  def index
    @events = Schedule.upcoming(current_time - 6.months).of_type(Event).map{|item| item.schedulable}.uniq

    respond_to do |format|
      format.html 
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @in_progress = Schedule.in_progress(current_time).of_schedulable(@event).map{ |i| i.get_ultimate_parent }.uniq
    @upcoming = Schedule.upcoming(current_time).of_schedulable(@event).map{ |i| i.get_ultimate_parent }.uniq

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event], :html => {:multipart => true} do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div style="margin: 10px;">

	<div class="field">
		<%= f.file_field :logo %>
	</div>	

	<div class="field">
		<%= f.label :remote_logo_url, "or image URL", :style => "font: bold 10pt helvetica;"  %><br />
		<%= f.text_field :remote_logo_url, :style => "width: 280px;" %>
	</div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

<div class="form_addition">
	<p class="form_addition_header">Web Links:</p>
	<%= link_to_add_fields "Add Link", f, :links %>
    <%= f.fields_for :links do |builder| %>
    	<%= render "link_fields", :f => builder %>
    <% end %>
</div>  

  <div class="actions" style="padding: 20px 0;">
    <%= f.submit %>
  </div>

<% end %>
</div>

app/views/admin/events/_link_fields.html.erb
<div class="dynamic_fields">
	<%= f.collection_select(:weblocation_id, @weblocations, :id, :name)%><%= f.text_field :url %><%= f.hidden_field :_destroy %><%= link_to_function "remove", "remove_fields(this)" %>
</div>  

app/views/admin/events/edit.html.erb
<h2>Edit Event</h2>
<%= render 'form' %>

app/views/admin/events/index.html.erb
<h2>Events Admin - <span class="signout"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></span></h2>
 
<table>
  <tr class="child">
    <td colspan="5"><%= link_to 'New Event', new_admin_event_path %></td>
  </tr>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th colspan="3">Functions</th>
  </tr>
 
<% @events.each do |event| %>
  <tr class="parent">
    <td><%= event.id %></td>
    <td><%= event.name %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_admin_event_path(event) %></td>
    <td><%= link_to 'Remove', [:admin, event], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

</table>

app/views/admin/events/new.html.erb
<h2>New Event</h2>
<%= render 'form' %>