config/routes.rb
Dewey::Application.routes.draw do

  match '/', :to => redirect('/index.html')
  devise_for :users

  resources :acts
  resources :events
  resources :festivals
  resources :schedules do
      get 'page/:page', :action => :index, :on => :collection
    end
  resources :venues
  
  namespace :admin do
    resources :acts
    resources :events
    resources :festivals
    resources :schedules
    resources :venues
    resources :weblocations
  end
  match "/admin/schedules/new_child/:parent_id(.:format)" => "admin/schedules#new_child", :as => :new_admin_child 

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  validates_presence_of :order

  belongs_to :schedulable, :polymorphic => true
  belongs_to :location

  has_many :children, :class_name => "Schedule", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Schedule", :foreign_key => "parent_id"
  
  has_many :links, :as => :linkable, :dependent => :destroy
  has_many :weblocations, :through => :links
  accepts_nested_attributes_for :links, :reject_if => lambda { |a| a[:url].blank? }, :allow_destroy => true
  
  has_many :details, :dependent => :destroy
  accepts_nested_attributes_for :details, :allow_destroy => true
  
  belongs_to :festival
  
  scope :all_parents, lambda { where(:parent_id => nil)}
  scope :in_progress, lambda {|date| where("(schedules.start <= ? AND schedules.end is not null AND schedules.end > ?) OR (schedules.end is null AND schedules.start < ? AND schedules.start > ?)", date, date, date, date - 3.hours) }
  scope :upcoming, lambda { |date| order(:start).where("start > ?", date) }
  scope :at_venue, lambda { |venue| scoped( :conditions => { :location_id => venue.locations} ).order( :start )  }
  scope :at_festival, lambda { |festival| scoped( :conditions => { :festival_id => festival} ).order( :start )  }
  scope :of_schedulable, lambda { |schedulable| scoped( :conditions => { :schedulable_id => schedulable.id, :schedulable_type => schedulable.class.name } ).order( :start ).reject{ |i| i == schedulable } }
  scope :of_type, lambda { |type| scoped( :conditions => { :schedulable_type => type } ).order( :start )}
    
  def is_parent?
    parent_id == nil
  end  
  
  def get_ultimate_parent
    node = self
    while node.parent_id != nil do
      node = Schedule.find(node.parent_id)
    end
    node
  end
  
  def self.children_that_are_not_same_as(parent)
    parent.children.select{ |c| c.schedulable_id != parent.schedulable_id || c.schedulable_type != parent.schedulable_type }
  end
  
  def self.children_that_are_same_as(parent)
    parent.children.select{ |c| c.schedulable_id == parent.schedulable_id && c.schedulable_type == parent.schedulable_type }
  end
      
  def agenda
    different_children = Schedule.children_that_are_not_same_as(self)
    different_children.sort_by{ |c| [c.order, (c.start.present?) ? c.start : c.parent.start] }.group_by{ |c| [c.schedulable_id, c.schedulable_type] }
  end
  
  def self.retrieve(schedulable_id, schedulable_type)
    schedulable_type.constantize.send("find", schedulable_id)
  end

  def acts
    children.map(&:schedulable).uniq(&:name).sort_by(&:name)
  end
  
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_locations
  layout 'admin'

  # GET /admin/schedules
  # GET /admin/schedules.json
  def index
    @parents = Schedule.all_parents.sort_by(&:start)
    @venues = Venue.all.sort_by{ |v| v.name.upcase }    
    respond_to do |format|
      format.html 
      format.json { render :json => @parents }
    end
  end

  # GET /admin/schedules/new
  # GET /admin/schedules/new.json
  def new
    @schedule = Schedule.new
    current_time
    @schedule.start = DateTime.civil(current_time.year, current_time.month, current_time.day, 21, 00, 0, "-4")    
    @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @schedulables = @acts = Act.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @events = Event.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @festivals = Festival.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @schedule }
    end
  end

  # GET /admin/schedules/new_child
  # GET /admin/schedules/new_child.json
  def new_child
    @parent = Schedule.find(params[:parent_id])
    @schedule = @parent.children.build
    @schedule.start = @parent.start
    @schedule.end = @parent.end
    @schedule.location = @parent.location
    @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @acts = Act.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @events = Event.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @festivals = Festival.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @schedulables = @acts
  
    respond_to do |format|
      format.html # new_child.html.erb
      format.json { render :json => @schedule }
    end
  end

  # POST /admin/schedules
  # POST /admin/schedules.json
  def create_child
    @schedule = Schedule.new(params[:schedule])    

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_url, :notice => 'Schedule was successfully created.'  }
        format.json { render :json => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new_child" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /admin/schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
    @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @festivals = Festival.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @schedulables = @schedule.schedulable_type.camelize.constantize.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @parent = @schedule.parent

    respond_to do |format|
      if @parent
        format.html { render :action => "edit_child" }
      else
        format.html { render :action => "edit" }
      end
    end
    
  end

  # POST /admin/schedules
  # POST /admin/schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])    

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to :action => "index", :notice => 'Schedule was successfully updated.' }
        format.json { render :json => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/schedules/1
  # PUT /admin/schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])
    @schedulables = @schedule.schedulable_type.camelize.constantize.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @parent = @schedule.parent

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to :action => "index", :notice => 'Schedule was successfully updated.' }
        format.json { head :ok }
      else
        if @parent
          format.html { render :action => "edit_child" }
        else
          format.html { render :action => "edit" }
        end
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/schedules/1
  # DELETE /admin/schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    if @schedule.children.count > 0
      respond_to do |format|
        format.html { redirect_to admin_schedules_url, :alert => "Cannot delete this parent scheduled item #{@schedule.schedulable.name} because it has child items. Delete those first." } 
        format.json { head :ok }
      end
    else
      @schedule.destroy
      respond_to do |format|
        format.html { redirect_to admin_schedules_url, :alert => "Successfully deleted scheduled item #{@schedule.schedulable.name}" }
        format.json { head :ok }
      end
    end
  end

  private

  def get_locations
    @locations = Location.all.sort { |a, b| a.form_picker_name.downcase <=> b.form_picker_name.downcase }    
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  # should refactor this into a config file.
  PAGINATION_THRESHOLD = 20
  MOBILE_PAGE_SIZE = 7
  BROWSER_PAGE_SIZE = 1000

  # GET /schedules
  # GET /schedules.json
  def index
    all_parents_upcoming = Schedule.includes(:schedulable, :children, :festival, :details, :location => [:venue] ).all_parents.upcoming(current_time)
    parents_grouped_by_dates = all_parents_upcoming.group_by{|sched| sched.start.to_date}
    
    page_size = (request.user_agent =~ /[M|m]obile/) ? MOBILE_PAGE_SIZE : BROWSER_PAGE_SIZE  
    page, per = (all_parents_upcoming.count < PAGINATION_THRESHOLD) ? [1, nil] : [params[:page], page_size]
    dates = parents_grouped_by_dates.keys.sort
    @dates = Kaminari.paginate_array(dates).page(page).per(per)
    @upcoming = @dates.reduce([]){ |arr, date| arr += parents_grouped_by_dates[date] }
    @in_progress = Schedule.in_progress(current_time).map{ |i| i.get_ultimate_parent }.uniq.reject{ |i| i == @schedule }
            
    respond_to do |format|
      format.js { raise ActionController::RoutingError.new('Not Found') if params[:page].present? && params[:page].to_i > @dates.num_pages }
      format.html {flash[:notice] = params[:notice]}
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.where(:id => params[:id]).first
    @in_progress = Schedule.in_progress(current_time).of_schedulable(@schedule.schedulable).map{ |i| i.get_ultimate_parent }.uniq.reject{ |i| i == @schedule }
    @upcoming = Schedule.upcoming(current_time).of_schedulable(@schedule.schedulable).map{ |i| i.get_ultimate_parent }.uniq.reject{ |i| i == @schedule }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @schedule }
    end
  end

end

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper

  def display_time(datetime)    
    datetime.to_formatted_s(:long) if datetime.present?
  end

end

app/views/schedules/_schedule_list.html.erb
<%= content_tag :h2, title if title.present? %>

<% list.group_by{|s| s.start.to_date}.sort.each do |start_date, parent_items_for_date| %>
	<h3><%= date_and_times(start_date) %></h3>
	<%= render :partial => 'schedule_item', :collection => parent_items_for_date.sort_by{ |item| [item.start, item.location.venue.name] } %>
<% end %>

app/views/schedules/index.html.erb
<div id ="happening_now">
  <%= render_list(@in_progress, "inprogress", "Happening Now", 'shared/schedule_item') %>
</div>

<div id="paginated_upcoming">
  <div class="sausage_page">
    <%= render_list(@upcoming, "upcoming", nil, 'shared/schedule_item') %>
  </div>
</div>

<div id="paginate_loading" style="display: none"><img src="<%= asset_path 'loading-small.gif' %>"></div>


<%= paginate @dates %>

app/views/schedules/index.js.erb
function resizeRolodex(height, width) {
  var viewportWidth = $(window).width();
  var viewportHeight = $(window).height();
  
  // alert("Setting height to " + viewportHeight);
  $("#rolodex").height(viewportHeight);
}

$().ready(resizeRolodex);
$(window).resize(resizeRolodex);

$("#paginated_upcoming").append("<div class='sausage_page'><%= escape_javascript(render_list(@upcoming, "upcoming", nil, 'shared/schedule_item') ) %></div>");

app/views/schedules/show.html.erb
<% @title = @schedule.schedulable.name %>
<div class="specificHeader">
	<div id="side">
		<%= logo_image(@schedule.schedulable, :class => "large") %>
		<%= content_tag :p, "Links for #{@schedule.schedulable.name}:", :class => "visit" if @schedule.schedulable.links.present? %>
		<% @schedule.schedulable.links.sort_by{|schedulable| schedulable.weblocation.popularity}.each do |link| %>
			<%= make_link(link) %>
		<% end %>
		<% @schedule.links.each do |link| %>
			<%= make_link(link) %>
		<% end %>
	</div>
	<div class="infoShow">
    <%= content_tag :h5, @schedule.schedulable.name %>
    <%= content_tag :p,  @schedule.schedulable.hometown,   :class => "hometown" if @schedule.festival_id.present? %>
    <%= content_tag :p,  @schedule.festival.name,          :class => "festival" if @schedule.festival_id.present? %>
		<%= content_tag :p,  @schedule.location.display_name,  :class => "location" if @schedule.location.display_name.present?  %>
    <%= content_tag :p,  date_and_times(@schedule.start) + ", " + times(@schedule), :class => "dates" %>
		<div class="description" id="venue_collapsable">
			<%= textilize(@schedule.schedulable.description) %>
		</div>
			
    <%= content_tag :p, "Additional Details:" unless @schedule.details.empty? %>
		<% @schedule.details.sort_by(&:order).each do |detail| %>
			<div class="addDetails">
				<p><strong><%= detail.name %></strong><%= detail.description.present? ? ": " : "" %><%= detail.description %></p>
			</div>				
		<% end %>

  </div>
		
</div>

<% if @schedule.festival.present? %>
	<h2>Festival</h2>
		<%= link_to festival_path(@schedule.festival), :class => "list_box" do %>
		<%= logo_image(@schedule.festival, :class => "list") %>
		<h5 class="oneline"><%= @schedule.festival.name %></h5>	
	<% end %>
<% end %>

<% if @schedule.location.present? %>
	<h2>Venue</h2>
		<%= link_to venue_path(@schedule.location.venue), :class => "list_box" do %>
		<%= logo_image(@schedule.location.venue, :class => "list") %>
		<h5 class="oneline"><%= @schedule.location.venue.name %></h5>	
	<% end %>
<% end %>

<%= content_tag :h2, "Acts" unless @schedule.children.empty? %>
<% @schedule.acts.each do |act| %>
	<%= link_to act_path(act), :class => "list_box" do %>
  	<%= logo_image(act, :class => "list") %>
  	<h5 class="oneline"><%= act.name %></h5>	
	<% end %>
<% end %>

<%= render_list(@in_progress, "inprogress", "Happening Now", 'shared/schedule_item') %>

<%= render_list(@upcoming, "upcoming", "Upcoming for #{@schedule.schedulable.name} (#{pluralize(@upcoming.count, 'show')})", 'shared/schedule_item') %>