config/routes.rb
Dewey::Application.routes.draw do

  match '/', :to => redirect('/index.html')
  devise_for :users

  resources :acts
  resources :events
  resources :festivals
  resources :schedules do
      get 'page/:page', :action => :index, :on => :collection
    end
  resources :venues
  
  namespace :admin do
    resources :acts
    resources :events
    resources :festivals
    resources :schedules
    resources :venues
    resources :weblocations
  end
  match "/admin/schedules/new_child/:parent_id(.:format)" => "admin/schedules#new_child", :as => :new_admin_child 

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  validates_presence_of :order

  belongs_to :schedulable, :polymorphic => true
  belongs_to :location

  has_many :children, :class_name => "Schedule", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Schedule", :foreign_key => "parent_id"
  
  has_many :links, :as => :linkable, :dependent => :destroy
  has_many :weblocations, :through => :links
  accepts_nested_attributes_for :links, :reject_if => lambda { |a| a[:url].blank? }, :allow_destroy => true
  
  has_many :details, :dependent => :destroy
  accepts_nested_attributes_for :details, :allow_destroy => true
  
  belongs_to :festival
  
  scope :all_parents, lambda { where(:parent_id => nil)}
  scope :in_progress, lambda {|date| where("(schedules.start <= ? AND schedules.end is not null AND schedules.end > ?) OR (schedules.end is null AND schedules.start < ? AND schedules.start > ?)", date, date, date, date - 3.hours) }
  scope :upcoming, lambda { |date| order(:start).where("start > ?", date) }
  scope :at_venue, lambda { |venue| scoped( :conditions => { :location_id => venue.locations} ).order( :start )  }
  scope :at_festival, lambda { |festival| scoped( :conditions => { :festival_id => festival} ).order( :start )  }
  scope :of_schedulable, lambda { |schedulable| scoped( :conditions => { :schedulable_id => schedulable.id, :schedulable_type => schedulable.class.name } ).order( :start ).reject{ |i| i == schedulable } }
  scope :of_type, lambda { |type| scoped( :conditions => { :schedulable_type => type } ).order( :start )}
    
  def is_parent?
    parent_id == nil
  end  
  
  def get_ultimate_parent
    node = self
    while node.parent_id != nil do
      node = Schedule.find(node.parent_id)
    end
    node
  end
  
  def self.children_that_are_not_same_as(parent)
    parent.children.select{ |c| c.schedulable_id != parent.schedulable_id || c.schedulable_type != parent.schedulable_type }
  end
  
  def self.children_that_are_same_as(parent)
    parent.children.select{ |c| c.schedulable_id == parent.schedulable_id && c.schedulable_type == parent.schedulable_type }
  end
      
  def agenda
    different_children = Schedule.children_that_are_not_same_as(self)
    different_children.sort_by{ |c| [c.order, (c.start.present?) ? c.start : c.parent.start] }.group_by{ |c| [c.schedulable_id, c.schedulable_type] }
  end
  
  def self.retrieve(schedulable_id, schedulable_type)
    schedulable_type.constantize.send("find", schedulable_id)
  end

  def acts
    children.map(&:schedulable).uniq(&:name).sort_by(&:name)
  end
  
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_locations
  layout 'admin'

  # GET /admin/schedules
  # GET /admin/schedules.json
  def index
    @parents = Schedule.all_parents.sort_by(&:start)
    @venues = Venue.all.sort_by{ |v| v.name.upcase }    
    respond_to do |format|
      format.html 
      format.json { render :json => @parents }
    end
  end

  # GET /admin/schedules/new
  # GET /admin/schedules/new.json
  def new
    @schedule = Schedule.new
    current_time
    @schedule.start = DateTime.civil(current_time.year, current_time.month, current_time.day, 21, 00, 0, "-4")    
    @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @schedulables = @acts = Act.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @events = Event.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @festivals = Festival.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @schedule }
    end
  end

  # GET /admin/schedules/new_child
  # GET /admin/schedules/new_child.json
  def new_child
    @parent = Schedule.find(params[:parent_id])
    @schedule = @parent.children.build
    @schedule.start = @parent.start
    @schedule.end = @parent.end
    @schedule.location = @parent.location
    @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @acts = Act.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @events = Event.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @festivals = Festival.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @schedulables = @acts
  
    respond_to do |format|
      format.html # new_child.html.erb
      format.json { render :json => @schedule }
    end
  end

  # POST /admin/schedules
  # POST /admin/schedules.json
  def create_child
    @schedule = Schedule.new(params[:schedule])    

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_url, :notice => 'Schedule was successfully created.'  }
        format.json { render :json => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new_child" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /admin/schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
    @weblocations = Weblocation.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @festivals = Festival.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @schedulables = @schedule.schedulable_type.camelize.constantize.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @parent = @schedule.parent

    respond_to do |format|
      if @parent
        format.html { render :action => "edit_child" }
      else
        format.html { render :action => "edit" }
      end
    end
    
  end

  # POST /admin/schedules
  # POST /admin/schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])    

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to :action => "index", :notice => 'Schedule was successfully updated.' }
        format.json { render :json => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/schedules/1
  # PUT /admin/schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])
    @schedulables = @schedule.schedulable_type.camelize.constantize.all.sort{ |a, b| a.name.downcase <=> b.name.downcase }
    @parent = @schedule.parent

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to :action => "index", :notice => 'Schedule was successfully updated.' }
        format.json { head :ok }
      else
        if @parent
          format.html { render :action => "edit_child" }
        else
          format.html { render :action => "edit" }
        end
        format.json { render :json => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/schedules/1
  # DELETE /admin/schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    if @schedule.children.count > 0
      respond_to do |format|
        format.html { redirect_to admin_schedules_url, :alert => "Cannot delete this parent scheduled item #{@schedule.schedulable.name} because it has child items. Delete those first." } 
        format.json { head :ok }
      end
    else
      @schedule.destroy
      respond_to do |format|
        format.html { redirect_to admin_schedules_url, :alert => "Successfully deleted scheduled item #{@schedule.schedulable.name}" }
        format.json { head :ok }
      end
    end
  end

  private

  def get_locations
    @locations = Location.all.sort { |a, b| a.form_picker_name.downcase <=> b.form_picker_name.downcase }    
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  # should refactor this into a config file.
  PAGINATION_THRESHOLD = 20
  MOBILE_PAGE_SIZE = 7
  BROWSER_PAGE_SIZE = 1000

  # GET /schedules
  # GET /schedules.json
  def index
    all_parents_upcoming = Schedule.includes(:schedulable, :children, :festival, :details, :location => [:venue] ).all_parents.upcoming(current_time)
    parents_grouped_by_dates = all_parents_upcoming.group_by{|sched| sched.start.to_date}
    
    page_size = (request.user_agent =~ /[M|m]obile/) ? MOBILE_PAGE_SIZE : BROWSER_PAGE_SIZE  
    page, per = (all_parents_upcoming.count < PAGINATION_THRESHOLD) ? [1, nil] : [params[:page], page_size]
    dates = parents_grouped_by_dates.keys.sort
    @dates = Kaminari.paginate_array(dates).page(page).per(per)
    @upcoming = @dates.reduce([]){ |arr, date| arr += parents_grouped_by_dates[date] }
    @in_progress = Schedule.in_progress(current_time).map{ |i| i.get_ultimate_parent }.uniq.reject{ |i| i == @schedule }
            
    respond_to do |format|
      format.js { raise ActionController::RoutingError.new('Not Found') if params[:page].present? && params[:page].to_i > @dates.num_pages }
      format.html {flash[:notice] = params[:notice]}
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.where(:id => params[:id]).first
    @in_progress = Schedule.in_progress(current_time).of_schedulable(@schedule.schedulable).map{ |i| i.get_ultimate_parent }.uniq.reject{ |i| i == @schedule }
    @upcoming = Schedule.upcoming(current_time).of_schedulable(@schedule.schedulable).map{ |i| i.get_ultimate_parent }.uniq.reject{ |i| i == @schedule }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @schedule }
    end
  end

end

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper

  def display_time(datetime)    
    datetime.to_formatted_s(:long) if datetime.present?
  end

end

app/views/admin/schedules/_child_form.html.erb
<%= form_for [:admin, @schedule] do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% @schedule.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="Act_options">  
  	<%= options_from_collection_for_select(Act.all, :id, :name) %>
  </div>

  <div id="Event_options">
  	<%= options_from_collection_for_select(Event.all, :id, :name) %>
  </div>

  <div style="margin: 10px;">

    <div class="field">
      <%= f.label 'Select a schedulable child' %><br />
      <%= f.select(:schedulable_type, ["Act", "Event"]) %><%= f.collection_select(:schedulable_id, @schedulables, :id, :name)%>
    </div>

    <div class="field">
      <%= f.label 'Select Venue/Location' %><br />
    	<%= f.collection_select(:location_id, @locations, :id, :form_picker_name)%>
    </div>

 <div class="field">
	<%= f.label :start %><br />
	<%= f.datetime_select :start, :include_blank => true  %> <%= submit_tag "Clear", :type => 'button', :id => 'clear_start' %> <%= submit_tag "Pull from Parent", :type => 'button', :id => 'parent_start' %>
 </div>

 <div class="field">
	<%= f.label :end %><br />
	<%= f.datetime_select :end, :id => 'end_select', :include_blank => true  %> <%= submit_tag "Clear", :type => 'button', :id => 'clear_end' %> <%= submit_tag "Pull from Parent", :type => 'button', :id => 'parent_end' %>
 </div>

 <div class="field">
	<%= f.label :display_time %>
	<%= f.check_box :display_time %>
 </div>
 <br />
	
 <div class="field">
	<%= f.label :order %><br />
	<%= f.text_field :order %>
 </div>

  	<%= f.hidden_field :parent_id %>

  <div class="actions" style="padding: 20px 0;">
    <%= f.submit %>
  </div>

  </div>


<% end %>

<script type="text/javascript">
    $(document).ready(function(){
		$("#clear_start").click(function(){
			$("#schedule_start_1i").val('');
			$("#schedule_start_2i").val('');
			$("#schedule_start_3i").val('');
			$("#schedule_start_4i").val('');
			$("#schedule_start_5i").val('');
			return false;
		});
		$("#clear_end").click(function(){
			$("#schedule_end_1i").val('');
			$("#schedule_end_2i").val('');
			$("#schedule_end_3i").val('');
			$("#schedule_end_4i").val('');
			$("#schedule_end_5i").val('');
			return false;
		});
		$("#parent_start").click(function(){
			$("#schedule_start_1i").val('<%= @parent.start.year %>');
			$("#schedule_start_2i").val('<%= @parent.start.month %>');
			$("#schedule_start_3i").val('<%= @parent.start.day %>');
			$("#schedule_start_4i").val('<%= @parent.start.strftime("%H") %>');
			$("#schedule_start_5i").val('<%= @parent.start.strftime("%M") %>');
			return false;
		});		
		$("#parent_end").click(function(){
			$("#schedule_end_1i").val('<%= @parent.end.present? ? @parent.end.year : "" %>');
			$("#schedule_end_2i").val('<%= @parent.end.present? ? @parent.end.month : "" %>');
			$("#schedule_end_3i").val('<%= @parent.end.present? ? @parent.end.day : "" %>');
			$("#schedule_end_4i").val('<%= @parent.end.present? ? @parent.end.strftime("%H") : "" %>');
			$("#schedule_end_5i").val('<%= @parent.end.present? ? @parent.end.strftime("%M") : "" %>');
			return false;
		});
        $("select#schedule_schedulable_type").change(populate_schedulables);
    });
</script>

app/views/admin/schedules/_detail_fields.html.erb
<div class="dynamic_fields">
  <p><%= f.label 'Name' %><br />
	<%= f.text_field :name %></p>
  <p><%= f.label 'Order' %><br />
	<%= f.text_field :order %></p>
  <p><%= f.label 'Description' %><br />
	<%= f.text_area :description %></p>
	<%= f.hidden_field :_destroy %><%= link_to_function "remove", "remove_fields(this)" %>
</div>  

app/views/admin/schedules/_form.html.erb
<%= form_for [:admin, @schedule] do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div id="Act_options">  
	<%= options_from_collection_for_select(Act.all, :id, :name) %>
</div>

<div id="Event_options">
	<%= options_from_collection_for_select(Event.all, :id, :name) %>
</div>

<h3>Schedule A Parent</h3>
<div style="margin: 10px;">

  <div class="field">
    <%= f.label 'Select a schedulable parent' %><br />
  	<%= f.select(:schedulable_type, ["Act", "Event"]) %><%= f.collection_select(:schedulable_id, @schedulables, :id, :name)%>
  </div>

  <div class="field">
    <%= f.label 'Select Venue/Location' %><br />
  	<%= f.collection_select(:location_id, @locations, :id, :form_picker_name)%>
  </div>

  <div class="field">
    <%= f.label 'Optionally select a Festival' %><br />
  	<%= f.collection_select(:festival_id, @festivals, :id, :name, :include_blank => true )%>
  </div>

 <div class="field">
	<%= f.label :start %><br />
	<%= f.datetime_select :start %>
 </div>

 <div class="field">
	<%= f.label :end %><br />
	<%= f.datetime_select :end, :id => 'end_select', :include_blank => true  %> <%= submit_tag "Copy Start", :type => 'button', :id => 'copy_start' %> <%= submit_tag "Clear", :type => 'button', :id => 'clear_end' %>
 </div>

 <div class="field">
	<%= f.label :display_time %>
	<%= f.check_box :display_time %>
 </div>

  <%= f.hidden_field :parent_id %>

	<div class="form_addition">
		<p class="form_addition_header">Web Links</p>
		<%= link_to_add_fields "Add Link", f, :links %>
		<%= f.fields_for :links do |builder| %>
			<%= render "link_fields", :f => builder %>
		<% end %>
	</div>  

	<div class="form_addition">
		<p class="form_addition_header">Additional Details</p>
		<%= link_to_add_fields "Add Details", f, :details %>
		<%= f.fields_for :details do |builder| %>
			<%= render "detail_fields", :f => builder %>
		<% end %>
	</div>  

<div class="actions" style="padding: 20px 0;">
<%= f.submit %>
</div>

</div>


<% end %>

<script type="text/javascript">
    $(document).ready(function(){
        $("select#schedule_schedulable_type").change(populate_schedulables);
    });
</script>


<script type="text/javascript">
    $(document).ready(function(){
		$("#clear_end").click(function(){
			$("#schedule_end_1i").val('');
			$("#schedule_end_2i").val('');
			$("#schedule_end_3i").val('');
			$("#schedule_end_4i").val('');
			$("#schedule_end_5i").val('');
			return false;
		});
		$("#copy_start").click(function(){
      var date = new Date($("#schedule_start_1i").val(), $("#schedule_start_2i").val()-1,  $("#schedule_start_3i").val(), 1, 0);
      var newDate = new Date(date.getTime() + 24*60*60*1000);
			$("#schedule_end_1i").val(newDate.getFullYear());
			$("#schedule_end_2i").val(newDate.getMonth()+1);
			$("#schedule_end_3i").val(newDate.getDate());
			$("#schedule_end_4i").val("01");
			$("#schedule_end_5i").val("00");
			return false;
		});
        $("select#schedule_schedulable_type").change(populate_schedulables);
    });
</script>

app/views/admin/schedules/_link_fields.html.erb
<div class="dynamic_fields">
	<%= f.collection_select(:weblocation_id, @weblocations, :id, :name)%><%= f.text_field :url %><%= f.hidden_field :_destroy %><%= link_to_function "remove", "remove_fields(this)" %>
</div>  

app/views/admin/schedules/edit.html.erb
<h2>Editing Schedule</h2>
<%= render 'form' %>

app/views/admin/schedules/edit_child.html.erb
<h2>Editing Child</h2>
<%= render 'child_form' %>

app/views/admin/schedules/index.html.erb
<h2>Schedule Admin - <span class="signout"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></span></h2>
<div class="options">
<%= link_to 'New Parent Item', new_admin_schedule_path %><br />
<ul class="venues" style="list-style-type: none;" >
  <li>
    <%= check_box_tag 'past', 'past', {:checked => true} -%> Past Events
  </li>
  <li>
    <%= check_box_tag 'present', 'present', {:checked => true} -%> Current Events
  </li>
  <li>
    <%= check_box_tag 'future', 'future', {:checked => true} -%> Future Events
  </li>
</ul>


<ul class="venues" style="list-style-type: none;" >
<% @venues.each do |venue| %>
  <li>
    <%= check_box_tag venue.name.to_s.parameterize.underscore, venue.name.to_s.parameterize.underscore -%>
    <%= venue.name.to_s %>
  </li>
<% end %>
</ul>
</div>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Venue</th>
    <th>Start</th>
    <th>End</th>
    <th>Order</th>	  
    <th colspan="4">Functions</th>
  </tr>
 
  <% @parents.each do |parent| %>
  <%= content_tag :tr, :class => "parent #{past_present_future(parent.start)} #{parent.location.venue.name.to_s.parameterize.underscore}" do  %>
      <td><%= parent.id %></td>
      <td><%= parent.schedulable.name %></td>
      <td><%= parent.location.form_picker_name %></td>
      <td><%= display_time(parent.start) %></td>
      <td><%= display_time(parent.end) %></td>
      <td><%= parent.order %></td>
      <td><%= link_to 'Show', parent %></td>
      <td><%= link_to 'Edit', edit_admin_schedule_path(parent) %></td>
      <td><%= link_to 'Add Child', new_admin_child_path(parent) %></td>
      <td><%= link_to 'Remove', [:admin, parent], :confirm => 'Are you sure?', :method => :delete %></td>
  <% end %>
    <% parent.children.each do |child| %>
  <%= content_tag :tr, :class => "child parent #{past_present_future(child.parent.start)} #{child.parent.location.venue.name.to_s.parameterize.underscore}" do  %>
        <td><%= child.id %></td>
        <td style="padding-left: 50px;"><%= child.schedulable.name %></td>
        <td><%= child.location.form_picker_name %></td>
        <td><%= display_time(child.start) %></td>
        <td><%= display_time(child.end) %></td>
        <td><%= child.order %></td>
        <td><!--<%= link_to 'Show', child %>--></td>
        <td><%= link_to 'Edit', edit_admin_schedule_path(child) %></td>
        <td></td>
        <td><%= link_to 'Remove', [:admin, child], :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    <% end %>
  <% end %>
</table>

<script type="text/javascript">
    $(document).ready(function(){    
    $('input').each(function(idx, item){
      $(item).click(function(){
        if ($(this).is(":checked"))
        {
          $("."+item.id).show();          
        }
        else
        {
          $("."+item.id).hide();          
        }
      });
    });
    
    });
</script>

app/views/admin/schedules/new.html.erb
<h2>New Parent</h2>
<%= render 'form' %>

app/views/admin/schedules/new_child.html.erb
<h2>New Child for <%= @parent.schedulable.name %></h2>
<%= render 'child_form' %>