config/routes.rb
Dewey::Application.routes.draw do

  match '/', :to => redirect('/index.html')
  devise_for :users

  resources :acts
  resources :events
  resources :festivals
  resources :schedules do
      get 'page/:page', :action => :index, :on => :collection
    end
  resources :venues
  
  namespace :admin do
    resources :acts
    resources :events
    resources :festivals
    resources :schedules
    resources :venues
    resources :weblocations
  end
  match "/admin/schedules/new_child/:parent_id(.:format)" => "admin/schedules#new_child", :as => :new_admin_child 

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>iDewIt Admin</title>

    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
  	<meta name="apple-mobile-web-app-capable" content="yes" />
    <link rel="apple-touch-icon" href=<%= asset_path 'icon.png' %> />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body onLoad="init()">

<h1>iDewIt Admin</h1>
<a href="javascript:history.back();"><img src="<%= asset_path 'back-button.png' %>" style="position: absolute; top: 7px; left: 10px; border: none;"></a>
<a href="/schedules/"><img src="<%= asset_path 'public-button.png' %>" style="position: absolute; top: 7px; right: 10px; border: none;"></a>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<div id="footnotes_holder"></div>

<p class="copyright">&copy; 2012-2015 Awkward Fist Bump Software</p>


<div id="tabbarbg">
	<div id="tabbarAdmin">
		<%= link_to("Schedule", admin_schedules_path, {:class => admin_page_class('schedules')}) %>
		<%= link_to("Acts", admin_acts_path, {:class => admin_page_class('acts')}) %>
		<%= link_to("Events", admin_events_path, {:class => admin_page_class('events')}) %>
		<%= link_to("Venues", admin_venues_path, {:class => admin_page_class('venues')}) %>
		<%= link_to("Festivals", admin_festivals_path, {:class => admin_page_class('festivals')}) %>
		<%= link_to("Weblocations", admin_weblocations_path, {:class => admin_page_class('weblocations')}) %>
	</div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>iDewIt</title>

    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=0;" />
  	<meta name="apple-mobile-web-app-capable" content="yes" />
    <link rel="apple-touch-icon" href=<%= asset_path 'icon.png' %> />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body onLoad="init()">

<h1><%= @title || "iDewIt" %></h1>
<a href="javascript:history.back();"><img src="<%= asset_path 'back-button.png' %>" style="position: absolute; top: 7px; left: 10px; border: none;"></a>
<% if user_signed_in? %>
	<a href="/admin/schedules/"><img src="<%= asset_path 'admin-button.png' %>" style="position: absolute; top: 7px; right: 10px; border: none;"></a>
<% end %>
<div id="loading"><img src="<%= asset_path 'loading.gif' %>"></div>
<script>
	var ld=(document.all);
	var ns4=document.layers;
	var ns6=document.getElementById&&!document.all;
	var ie4=document.all;
	if (ns4)
		ld=document.loading;
	else if (ns6)
		ld=document.getElementById("loading").style;
	else if (ie4)
		ld=document.all.loading.style;
	function init()
		{
		if(ns4){ld.visibility="hidden";
		}
		else if (ns6||ie4) ld.display="none";
 		}
</script>

<%= yield %>

<div id="footnotes_holder"></div>

<p class="copyright">&copy; 2012-2015 Awkward Fist Bump Software</p>

<div id="tabbarbg">
	<div id="tabbar">
		<%= link_to("Schedule", schedules_path, {:class => page_class('schedules')}) %>
		<%= link_to("Acts", acts_path, {:class => page_class('acts')}) %>
		<%= link_to("Events", events_path, {:class => page_class('events')}) %>
		<%= link_to("Venues", venues_path, {:class => page_class('venues')}) %>
		<%= link_to("Festivals", festivals_path, {:class => page_class('festivals')}) %>
	</div>
</div>

</body>
</html>